add tenant token demo
meilisearch/demos pull request #23
Opened 2022-03-17 11:40 UTC by shivaylamba

# Pull Request

## What does this PR do?
Fixes #22 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-03-17 15:29 UTC, bidoubiwa commented on src/tenant-token/frontend/README.md
> +Runs the app in the development mode.\
```suggestion
Runs the app in the development mode.
```

There are a lot of backslashes, are they useful ?

2022-03-17 15:29 UTC, bidoubiwa commented on src/tenant-token/README.md
> + - [NodeJs](https://nodejs.org/en/download/)
You need to add `npm`

2022-03-18 09:58 UTC, shivaylamba commented on src/tenant-token/README.md
> +We will set up things in sequence to avoid dependencies.
That we need to follow the steps in sequence. I have removed the line to avoid confusion.

2022-03-18 10:02 UTC, shivaylamba commented
@bidoubiwa I have made the suggested changes.

2022-03-18 12:00 UTC, bidoubiwa requested changes

2022-03-18 12:58 UTC, shivaylamba commented on src/tenant-token/README.md
> + - [NodeJs](https://nodejs.org/en/download/)
Link to npm?

2022-03-18 14:31 UTC, bidoubiwa commented on src/tenant-token/README.md
> + - [NodeJs](https://nodejs.org/en/download/)
Yes!

2022-03-21 09:57 UTC, bidoubiwa approved these changes
LGTM 🔥🔥 Great Job

2022-03-21 11:01 UTC, shivaylamba commented
Thank you @bidoubiwa

2022-03-21 11:02 UTC, merged

2022-03-28 09:39 UTC, shivaylamba commented on src/tenant-token/.gitignore
> +
Can you add your reviews here @mdubus

2022-03-28 10:13 UTC, mdubus reviewed
You did a really great job with this demo, it works very well and I absolutely love it 🤩
So big congrats to you 👏

Here are a few points that I noticed:
- There are multiple theming solutions used here (Tailwind, pure css, and styled-system). Should we go for just one ?
- There are a lot of useless code, which could be cleaned

I know that this is just a demo and we don't really want to spend too much time on it, but from my point of view, if I want to know how you did this demo and I check the code, it's really hard to understand what's going on because of the amount of code, which can be reduced (removal of useless code). 
Plus, this demo is also Meilisearch's image, and by checking the code I have the feeling that some code was copy-pasted from somewhere else (which is the case for some components). As I worked on the mini-dashboard I know that the code comes from internally, but it may not be obvious for some curious external users who may check the code of this demo.

Maybe @ferdi05 could help us take a decision about this points ?

I really hope that one day we will have a template for demos like this, it would be so much easier for everybody ! ☺️

2022-03-28 13:37 UTC, nicolasvienot commented
Hello! Just passed by and I think there might be an issue with the Vercel configuration. You might want to check, this should display the folder `tenant-token` and not `src` :) Also could you rename the app from `demos-tenant-token` to `demo-tenant-token` in Vercel? Thanks!

<img width="915" alt="Capture d’écran 2022-03-28 à 15 34 26" src="https://user-images.githubusercontent.com/44903069/160409397-fdb0fd62-34ff-4640-a1db-363a92f29047.png">

Great job @shivaylamba :fire: