Updated Nobel prizes demo to v0.26
meilisearch/demos pull request #40
Opened 2022-04-16 20:52 UTC by oluademola

# Pull Request

## What does this PR do?
Fixes #<issue_number>

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-04-20 14:58 UTC, CaroFG requested changes
Need to replace snake_case with camelCase

2022-04-20 16:04 UTC, oluademola commented
All done, updated the MeiliSearch naming as well

2022-04-21 08:19 UTC, shivaylamba requested changes
<img width="597" alt="image" src="https://user-images.githubusercontent.com/19529592/164411667-7e1e8dc1-cd22-4cbc-903e-1e9d47b4899c.png">
Currently Moma Demo shows MeiliSearch instead of Meilisearch @CaroFG @oluademola

2022-04-21 08:22 UTC, shivaylamba approved these changes

2022-04-28 11:03 UTC, merged