css style guide for button, heading, input
meilisearch/demos pull request #95
Opened 2022-06-27 16:42 UTC by shivaylamba

# Pull Request

This PR introduces a sample CSS styleguide for maintaining consistency for styling in new demos. The style guide consists of CSS for common UI elements that can be used while creating a new demo for the demo repository.

2022-07-05 06:59 UTC, CaroFG requested changes
It would be much better if we used `rem` or `em` values instead of `px` Cf. [Sizing in CSS](https://chiamakaikeanyi.dev/sizing-in-css-px-vs-em-vs-rem/)

2022-07-05 06:59 UTC, CaroFG commented on process/css-styleguide/tag/index.html
> +        <div class="tag-loader"></div>
div (block-level element) should not be a child of a span (inline element)

2022-07-05 06:59 UTC, CaroFG commented on process/css-styleguide/tag/index.html
> +      >
end of tag should not be in a different  line

2022-07-12 06:58 UTC, shivaylamba commented
I have included a README
Added a file for spacing

2022-07-12 07:31 UTC, CaroFG requested changes
Corrected some typos. I saw you added a spacing file, really nice! 🔥 
Maybe you misunderstood what I meant when I told you to add some margin. I meant to add it to the actual HTML files because it renders like this:
![Capture d’écran 2022-07-12 à 09 31 32](https://user-images.githubusercontent.com/48251481/178434394-e71b5342-0147-4c47-9828-7a05f8c120fb.png)


It's just a detail, I know, but it's ugly and it doesn't take a lot of time or effort to improve it.

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +1. The Base class for styling the button is `.btn` that will set some basics stylings to button.
```suggestion
1. The base class for styling a button is `.btn`. It will set some basic stylings to the button.
```

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +2. Style Support : Change the color styling of the button by using classes like `.btn-dodger-blue`
```suggestion
2. Style support: change the color styling of the button by using classes like `.btn-dodger-blue`
```

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +1. The Base class for styling the heading is `.typography` that will assign font-styling to text.
```suggestion
1. The base class for styling the heading is `.typography`. It will assign font styling to text.
```

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +1.  The parent class `.input` will assign some basics styling to the input.
```suggestion
1.  The parent class `.input` will assign some basic styling to the input.
```

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +2.  Styling can also be given to labels depending upon varoius needs, some of the classes are `.input--label` `.input--message` `.input--message-error`
```suggestion
2.  Styling can also be given to labels depending upon various needs, some of the classes are `.input--label` `.input--message` `.input--message-error`
```

2022-07-12 07:31 UTC, CaroFG commented on process/css-styleguide/README.md
> +1. The class `.input-search` will give styling to search input and will also handles the events like active, focus and hover.
```suggestion
1. The class `.input-search` will give styling to search input and will also handle the events like active, focus, and hover.
```

2022-07-12 15:41 UTC, CaroFG requested changes

2022-07-12 15:41 UTC, CaroFG commented on process/css-styleguide/default.css
> +}
There is no newline at the end of the file

2022-07-12 15:41 UTC, CaroFG commented on process/css-styleguide/heading/heading.css
> +}
There is no newline at the end of the file

2022-07-12 15:41 UTC, CaroFG commented on process/css-styleguide/input/input.css
> +}
There is no newline at the end of the file

2022-07-12 15:41 UTC, CaroFG commented on process/css-styleguide/modal/modal.css
> +}
There is no newline at the end of the file

2022-07-12 15:41 UTC, CaroFG commented on process/css-styleguide/tag/index.html
> +</html>
There is no newline at the end of the file

2022-07-13 08:44 UTC, mdubus reviewed
Here are some problems that I noted: 

- The components doesn't match the design system we have. 
For instance, here are your buttons: 
<img width="833" alt="Capture d’écran 2022-07-13 à 09 52 16" src="https://user-images.githubusercontent.com/30866152/178681607-ccd89572-65be-4892-91b4-34c743359822.png">

Here are the ones of the design system:
<img width="382" alt="Capture d’écran 2022-07-13 à 09 57 15" src="https://user-images.githubusercontent.com/30866152/178681698-81098569-5f7b-41c9-b166-c652cf4caacd.png">

If we have a design system, we should stick to it no matter what, especially for demos. Here is the link of the design system juste in case: https://www.figma.com/file/XXmUvsZzfZBKt1i2v12wf4/Design-System
Plus, the colors of the screenshot doesn't seem to match the ones of the design system.

- By reading the readme, I don't know how to use this repo. Should I import a file somewhere? Do something else? This is not clear and should be specified somewhere.

- I don't get why you imported all these meilisearch logos. If they are useful for some reason, please explain it in the Readme.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/README.md
> +![Screenshot from 2022-07-11 15-08-37](https://user-images.githubusercontent.com/64376712/178236255-d999514e-50f9-4960-9958-497ce207d1ed.png)
Same as for the buttons, the image needs padding

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/README.md
> +   `.tag-sucess` `.tag-process` along with `.tag`
By reading this I don't know which classes are available. We need an exhaustive list.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/button/button.css
> +
Useless line

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/button/button.css
> +}
No `focus` state? 🥲 
Please never forget accessibility.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/button/index.html
> +    <h3 class="p-2">Disable</h3>
Why do you use `h3` ?

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/heading/heading.css
> +}
We have 2 font-family in the design system: `poppins` and `inter`. I suggest you add classes for these 2 fonts.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/heading/index.html
> +
Can you add margin instead of doing this?

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/heading/index.html
> +      This is Body L - Link
All the texts below are false:
<img width="265" alt="Capture d’écran 2022-07-13 à 10 18 21" src="https://user-images.githubusercontent.com/30866152/178685695-5ead966e-069a-430c-994d-f35ca6c52224.png">

They are specified as `body L` but they are not.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/input/index.html
> +      />
I don't get why you display twice the `error` variant: 
<img width="444" alt="Capture d’écran 2022-07-13 à 10 21 23" src="https://user-images.githubusercontent.com/30866152/178686329-4f175f97-f9fd-4737-b565-55859523b3a6.png">

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/modal/modal.css
> +}
The modal shouldn't change the background-color of the page. What if I want to use it on the landing page which has a `valhalla` background-color? This is gonna break the page style and it is not what we want.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/search-input/index.html
> +
You have a lot of empty lines in your project's files, please fix it :)

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/spacing.css
> +}
I think that you can make variables with all these values (`0.25rem`, `0.5rem`, ...). This way, if you want to update one of them someday, you only need to update it in one place and not everywhere.

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/tag/index.html
> +    <title>Tags / Pills</title>
Why `pills`? It is only mention of `tags` everywhere

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/tag/index.html
> +    </div>
You have here a mismatch between the text displayed and the class used: `success` vs `active`, `error` vs `inactive`, ...  It is not clear by reading it what would be displayed

2022-07-13 08:44 UTC, mdubus commented on process/css-styleguide/tag/tag.css
> +.tag-terminate {
I don't get what is a `terminate` variant

2022-07-21 10:06 UTC, shivaylamba commented
@mdubus 
>By reading the readme, I don't know how to use this repo. Should I import a file somewhere? Do something else? This is not clear and should be specified somewhere: 

There are few cases in which we may use this repository. For example if we want to use a button, we can directly import the CSS file for the button. But it might be unnecessary. Rather we could create a CDN for all the CSS files and directly import in our project. Else we can also create React component for these files.

2022-07-28 13:51 UTC, CaroFG requested changes
There are some changes yet to be done. 

It could be a nice addition to add a link to the[ _Guide to design a demo_](https://www.figma.com/file/YUqMlOmApYd0D2aitPyDce/Guide-to-design-a-demo?node-id=0%3A1)

2022-07-28 13:51 UTC, CaroFG commented on process/css-styleguide/button/button.css
> +.btn-secondary {
I don't think this class suits all, primary and secondary buttons use different colors for the different states (default, hover, and disabled). In the example, when you hover on the secondary button, the color applied is the color for the primary one
![Capture d’écran 2022-07-28 à 15 00 16](https://user-images.githubusercontent.com/48251481/181511246-10ca4bf0-5d2e-4618-a7d4-6e2f4f4eb766.png)

It should be
![Capture d’écran 2022-07-28 à 15 00 55](https://user-images.githubusercontent.com/48251481/181511318-79b22d37-4aec-4929-a2d8-84f193e9b8d3.png)

2022-07-28 13:51 UTC, CaroFG commented on process/css-styleguide/default.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap");
Poppins should be used for headings and Inter for the rest. Inter should also be imported in this file

2022-07-28 13:51 UTC, CaroFG commented on process/css-styleguide/heading/heading.css
> +.poppins {
As I said in the previous comment, "Poppins should be used for headings and Inter for the rest.". You could maybe get rid of the `.poppins` class and add directly the font-family to the `.typography` class. 

Also, there is no need of an `.inter` class in this file

2022-07-28 13:51 UTC, CaroFG commented on process/css-styleguide/input/index.html
> +      <span class="typography poppins body-xs input--message">Lorem Message</span>
`Lorem Message` and `Label` appear in the same line in the rendered HTML:
![Capture d’écran 2022-07-28 à 09 58 22](https://user-images.githubusercontent.com/48251481/181521263-70777eee-50e6-43ba-8852-21199e959beb.png)

2022-08-03 06:13 UTC, shivaylamba commented
Suggestion: Regarding the CSS Style guide, This could be a good reference: https://github.com/razorpay/blade
Essentially creating a Storybook for the Design guide

2022-08-23 07:54 UTC, closed without merging